### ISSUE TITLE
GPU support in field calculations

### ISSUE THREAD

**Issue by lmh91** [JuliaPhysics/SolidStateDetectors.jl#60]
### ToDo:
- [x] Support cylindrical coordinates
- [x] Support Cartesian coordinates
- [x] Support Depletion handling
- [x] Add Documentation
- [x] Add tests 

- [x] Test it on AMD GPUs
- [ ] How to choose a specific GPU device (-> using multiple GPUs in parallel)
- [x] Add convergence check for GPU backend
